---
- hosts: windows
  vars:
     services: "{{ lookup('csvfile', 'file=services.csv col=0 delimiter=,') }}"  
  tasks:
  - name: "Loop through Services"
    win_service:
      name: "{{ item }}"
    register: result
    failed_when: result is not defined
    #ignore_errors: yes
    with_items: 
     - "{{ services }}"

  - debug: msg="{{ item.results }}"
    with_items:
      - "{{ result }}"

  - debug: msg="running"
    when: result.state is not defined or result.name is not defined

